- name: Readtime
  description: Getting things read on your iPhone
- name: Eventer
  description: Changing what it’s like to watch an event you couldn’t make it to.
- name: Thread
  description: Helping Melbourne Business School to be leaders in digital learning.
- name: REA
  description: "Rebuilding the Customer Platform, ground up."
- name: Hooroo
  description: Bacon ipsum dolor sit amet short loin ball tip doner corned beef.
- name: Redbubble
  description: A marketplace for digital artists